=== strannik-mas/localhost/xslt/new XML-XSLT/module-2/demo-3.dtd
<!ELEMENT books (book+) >
<!ELEMENT book ((title, author+, price, publisher) | book+ ) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT publisher (#PCDATA) >
<!ENTITY bhv "BHV">
<!ENTITY will "Williams">
<!ENTITY apress "A-Press Publishing">

=== strannik-mas/localhost/xslt/new XML-XSLT/module-2/demo-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "demo-3.dtd">
<books>
	<book>
		<title>Название</title>
		<author>Автор</author>
		<price>123.00</price>
		<publisher>&apress;</publisher>
	</book>
	<book>
		<book>
			<title>Название</title>
			<author>Автор</author>
			<price>123.00</price>
			<publisher>&apress;</publisher>
		</book>
		<book>
			<title>Название</title>
			<author>Автор</author>
			<price>123.00</price>
			<publisher>&apress;</publisher>
		</book>
	</book>
</books>
