=== strannik-mas/localhost/xslt/new XML-XSLT/module-3/demo-3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:group name="personGroup">
		<xs:sequence>
			<xs:element name="id" type="xs:ID" />
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:group>

	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="customers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="customer" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:group ref="personGroup" />
										<xs:element name="addr" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
										
				</xs:element>
				<xs:element name="clerks">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="clerk" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:group ref="personGroup" />
										<xs:element name="office" type="xs:string" />
									</xs:sequence>
								</xs:complexType>							
							</xs:element>
						</xs:sequence>
					</xs:complexType>				
				</xs:element>	
			</xs:sequence>
		</xs:complexType>
	

	</xs:element>
</xs:schema>

=== strannik-mas/localhost/xslt/new XML-XSLT/module-3/demo-3.xml
<?xml version="1.0" encoding="utf-8"?>
<root 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="demo-3.xsd">
	
	<customers>
		<customer>
			<id>A-1</id>
			<name>Вася</name>
			<addr>Адрес</addr>
		</customer>
		<customer>
			<id>A-2</id>
			<name>Петя</name>
			<addr>Адрес</addr>
		</customer>	
	</customers>
	
	<clerks>
		<clerk>
			<id>B-1</id>
			<name>Саша</name>
			<office>Адрес</office>
		</clerk>
		<clerk>
			<id>B-2</id>
			<name>Сережа</name>
			<office>Адрес</office>
		</clerk>	
	</clerks>
	

	

</root>
