=== strannik-mas/localhost/xslt/new XML-XSLT/module-3/demo-4.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="ageType">
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="100" />
			<xs:minExclusive value="12" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="phoneType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{3}-?\d{2}-?\d{2}" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="birthday">
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:minInclusive value="1950-01-01" />
				<xs:maxInclusive value="2008-12-31" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:simpleType name="daysType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Воскресение" />
			<xs:enumeration value="Понедельник" />
			<xs:enumeration value="Вторник" />
			<xs:enumeration value="Среда" />
			<xs:enumeration value="Четверг" />
			<xs:enumeration value="Пятница" />
			<xs:enumeration value="Суббота" />
		</xs:restriction>
	</xs:simpleType>



	<!-- Описание самой структуры -->
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="customer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:ID" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="age" type="ageType" />
							<xs:element name="birthday" type="xs:date">
							<xs:element name="phone" type="phoneType" />
							<xs:element name="day" type="daysType" />

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== strannik-mas/localhost/xslt/new XML-XSLT/module-3/demo-4.xml
<?xml version="1.0" encoding="utf-8"?>
<root 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="demo-4.xsd">
	
	<customer>
		<id>A-2</id>
		<name>Петя</name>
		<age>24</age>
		<birthday>2008-05-12</birthday>
		<phone>240-45-45</phone>
		<day>Понедельник</day>
	</customer>	

</root>
